version: "3.3"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    volumes:
      - /usr/src/app/downloads:/usr/src/app/downloads:rw # optional
    ports:
      - "51:51" # qbittorrent selection webserver
      - "5151:5151" # rclone serve index webserver
    restart: on-failure
      
      
